export const ACHIEVEMENTS = [
  {
    id: 'first-focus',
    iconName: 'Target',
    label: 'First Focus',
    desc: 'Complete your first session',
    check: (s) => s.goalsCompleted >= 1,
  },
  {
    id: 'momentum',
    iconName: 'TrendingUp',
    label: 'Momentum',
    desc: '10 sessions completed',
    check: (s) => s.goalsCompleted >= 10,
    progress: (s) => ({ value: Math.min(s.goalsCompleted, 10), max: 10 }),
  },
  {
    id: 'sessions-30',
    iconName: 'BarChart2',
    label: 'The Grind',
    desc: '30 sessions completed',
    check: (s) => s.goalsCompleted >= 30,
    progress: (s) => ({ value: Math.min(s.goalsCompleted, 30), max: 30 }),
  },
  {
    id: 'century',
    iconName: 'Hash',
    label: 'The Century',
    desc: '100 sessions completed',
    check: (s) => s.goalsCompleted >= 100,
    progress: (s) => ({ value: Math.min(s.goalsCompleted, 100), max: 100 }),
  },
  {
    id: 'week-streak',
    iconName: 'Flame',
    label: 'On Fire',
    desc: '7-day streak',
    check: (s) => s.streak >= 7,
    progress: (s) => ({ value: Math.min(s.streak, 7), max: 7 }),
  },
  {
    id: 'streak-30',
    iconName: 'CalendarCheck',
    label: 'Relentless',
    desc: '30-day streak',
    check: (s) => s.streak >= 30,
    progress: (s) => ({ value: Math.min(s.streak, 30), max: 30 }),
  },
  {
    id: 'hour-marathon',
    iconName: 'Zap',
    label: 'Marathon',
    desc: '10 hours total focus',
    check: (s) => (s.totalFocusMinutes || 0) >= 600,
    progress: (s) => ({ value: Math.min(Math.floor((s.totalFocusMinutes || 0) / 60), 10), max: 10 }),
  },
  {
    id: 'time-lord',
    iconName: 'Clock',
    label: 'Time Lord',
    desc: '50 hours total focus',
    check: (s) => (s.totalFocusMinutes || 0) >= 3000,
    progress: (s) => ({ value: Math.min(Math.floor((s.totalFocusMinutes || 0) / 60), 50), max: 50 }),
  },
  {
    id: 'deep-work',
    iconName: 'Timer',
    label: 'Deep Work',
    desc: 'Complete a 60+ minute session',
    check: (_s, h) => h.some((s) => (s.minutes || 0) >= 60),
  },
  {
    id: 'scholar',
    iconName: 'BookOpen',
    label: 'Scholar',
    desc: 'Focus on 10+ different topics',
    check: (_s, h) =>
      new Set(h.map((s) => s.topic?.trim().toLowerCase()).filter(Boolean)).size >= 10,
    progress: (_s, h) => ({
      value: Math.min(new Set(h.map((s) => s.topic?.trim().toLowerCase()).filter(Boolean)).size, 10),
      max: 10,
    }),
  },
  {
    id: 'early-bird',
    iconName: 'Sunrise',
    label: 'Early Bird',
    desc: 'Start a session before 7am',
    check: (_s, h) => h.some((s) => new Date(s.date).getHours() < 7),
  },
  {
    id: 'night-owl',
    iconName: 'Moon',
    label: 'Night Owl',
    desc: 'Start a session after 10pm',
    check: (_s, h) => h.some((s) => new Date(s.date).getHours() >= 22),
  },
];
