name: Build & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: Aurora ${{ github.ref_name }}
          generate_release_notes: true

  release:
    needs: create-draft
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        env:
          VITE_FIREBASE_API_KEY: AIzaSyAtGuJ10S0dzXgD0BCXI8EQOSpS63OXnvQ
          VITE_FIREBASE_AUTH_DOMAIN: stay-aurora.firebaseapp.com
          VITE_FIREBASE_PROJECT_ID: stay-aurora
          VITE_FIREBASE_STORAGE_BUCKET: stay-aurora.firebasestorage.app
          VITE_FIREBASE_MESSAGING_SENDER_ID: "135860160624"
          VITE_FIREBASE_APP_ID: "1:135860160624:web:e378cac1bdc2c99299ccb5"
          VITE_FIREBASE_MEASUREMENT_ID: G-0QEHSFY5S2
          VITE_WEB_APP_URL: https://stayaurora.dev
        run: npm run build

      - name: Build and Publish Electron App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --publish always
